version: 0.94.{build}
os: Visual Studio 2022
clone_depth: 1

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails.

configuration:
- Debug
- Release
- Checked

platform:
- x86
- x64

before_build:
- set PATH=C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin;%PATH%

build_script:
- msbuild "C:\projects\msf\msf.sln" /m"

build:
  project: msf.sln
  verbosity: normal